apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andrii-bh-wp-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-dependency
    repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
    targetRevision: andrii-bh
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: andrii-bh-1
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
