apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drop-table
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
    targetRevision: vadym-test
  destination:
    name: in-cluster
    namespace: droptable
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
