apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: version-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/denis-codefresh/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: version-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
